export const TYPES = {
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_ALL_PRODUCTS:"REMOVE_ALL_PRODUCTS",
    REMOVE_ONE_PRODUCT:"REMOVE_ONE_PRODUCT",
    CLEAR_CART:"CLEAR_CART",
    ADD_PRODUCTS:"ADD_PRODUCTS"
}
